// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// IHandler is an autogenerated mock type for the IHandler type
type IHandler struct {
	mock.Mock
}

// Disburse provides a mock function with given fields: w, r
func (_m *IHandler) Disburse(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// DisburseList provides a mock function with given fields: w, r
func (_m *IHandler) DisburseList(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// UserDetail provides a mock function with given fields: w, r
func (_m *IHandler) UserDetail(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// NewIHandler creates a new instance of IHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *IHandler {
	mock := &IHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
